---
klaus:
  image: hiciu/klaus-dockerfile
  ports:
  - "8080:8080"
  volumes:
  - /srv/git:/srv/git
  - /etc/passwd:/etc/passwd:ro
  environment:
    KLAUS_SITE_NAME: klaus
    KLAUS_CTAGS_POLICY: tags-and-branches

    UWSGI_WSGI_FILE: wsgi_autoreload_ctags_ldap.py
    UWSGI_SETUID: 1000

    LDAP_SERVER: ldap.example.org
    LDAP_SEARCH_BASE: ou=developers,dc=example,dc=org
